### PR TITLE
more arguments added

### PR DESCRIPTION
**Pull request by chlsmith**
I added more arguments so I could create more specific Windows Firewall rules.   I still need to figure out how to make it work when the protocol is ICMPv4.   I can add it as an option and all, but the netsh command has different required options when you have ICMPv4 as the protocol.   

This is the first one I've ever messed with, so I'm just learning.   Maybe you can make use of some of the options I added.

### CODE REVIEW

**Comment by mattstratton** [comment]
One issue I see here is that you've put in a recipe in the cookbook itself just for testing purposes. For resource-only cookbooks, the pattern is to create fixture cookbooks for use in testing; this is the pattern @someara demonstrates in the https://github.com/chef-cookbooks/httpd cookbook.

If you take a look at my branch over here - https://github.com/mattstratton/windows_firewall/tree/ip_address you'll see a bit of how I did this.

The question is how we want to handle the merge. I'll submit a PR for what I have so far to the branch that @lynx44 created for your PR and we can see how crazy the diff is :)

**Comment by chlsmith** [comment]
It's my first github thing ever....feel free to beat the crap out of
whatever is wrong with it.   :)

**Comment by mattstratton** [comment]
I would say at this point we're just waiting for @lynx44 to pull in my PR and then I can pull that branch down and see what we've got :)

**Comment by mattstratton** [comment]
I merged down your commits and will do some manual cleanup and testing. I suggest that this PR be closed and I'll submit a new PR that includes @chlsmith changes and my own.

**Comment by mattstratton** [comment]
I've submitted a new PR #5 with your stuff merged into mine. This PR should probably be closed by @lynx44 after reviewing the new PR.

**Pull request merged**
